tfexec: Initial support for Terraform 0.14 -chdir global option
hashicorp/terraform-exec pull request #100
Opened 2020-10-19 16:42 UTC by bflad

Closes #99

2020-12-07 16:08 UTC, paultyng commented
Does `chdir` replace the work dir args that are in use in some plans already? We may need to look at this a bit more holistically, so we can utilize those options or something.

2021-02-02 19:00 UTC, bflad commented
@paultyng I believe so, please see https://github.com/hashicorp/terraform/pull/27664

2021-02-02 20:09 UTC, bflad commented
Rebased 👍  We will probably want to go through and mark all the removed "args" with `tf.compatible(ctx, nil, tf0_15_0)` as well -- happy to do that here or leave as a followup item.

2021-08-12 20:51 UTC, radeksimko requested changes
Sorry for the long delay in reviewing this @bflad - I finally found a spare moment to look at this PR of yours!

Do you have a use case (in SDK or elsewhere) for changing workdir during the lifetime of `*Terraform` instance?

I always worked with the assumption that the `*Terraform` is short-lived in a similar way to `context.Context`, which coincides with the fact that many commands didn't have an explicit argument (until recently) to run in a directory different to the one provided via `NewTerraform(workdir, ...)`.

I think it is fair to support both workflows, but I think it will require a little bit more effort involved to make this safe.

We currently persist `version` output in the struct
https://github.com/hashicorp/terraform-exec/blob/43ec6e17578bf2fd1e1037f9df5f1399d983eca8/tfexec/terraform.go#L56-L58
to be able to run compatibility checks without having to re-execute `version` repeatedly before each command.

The core version is (naturally) scoped to the Terraform binary (execPath), but the `version` command also outputs versions of providers which _are_ scoped to the workdir. I worry slightly that users won't realize this side effect while reading the cached output

https://github.com/hashicorp/terraform-exec/blob/43ec6e17578bf2fd1e1037f9df5f1399d983eca8/tfexec/version.go#L27-L36

Obviously this problem already exists given that we support the `dir` args in various commands already, but this is much more radical change which brings this problem more into spotlight IMO.

One way we could address this is by scoping the cache by workdir - as a map, or more likely as [`sync.Map`](https://pkg.go.dev/sync#Map) to make it safe for multiple commands to be executed at once. We should probably also consider some mechanism for purging the cache, like `Cleanup(workdir string)` - something that can be (optionally) called by downstream long-running process. This is to prevent any unnecessary memory consumption in case the consumer e.g. creates a high number of temporary directories in which it runs Terraform commands.

On a related note there is still a few commands which are missing the opts argument for passing `chdir`:
 - `ProvidersSchema`
 - `Version`
 - `Validate`

I think the `skipCache` argument should _probably_ stay there as 1st class argument (as opposed to being hidden under `opts ...VersionOption`) to communicate the side effect of the builtin cache.

> We will probably want to go through and mark all the removed "args" with tf.compatible(ctx, nil, tf0_15_0) as well -- happy to do that here

Yes please - if you can do that as part of this PR that would be great! 👍🏻

2021-08-12 20:51 UTC, radeksimko commented on tfexec/providers_schema.go
>  func (tf *Terraform) ProvidersSchema(ctx context.Context) (*tfjson.ProviderSchemas, error) {
I think in order to actually expose the `chdir` flag here we'd need to introduce `opts ...ProvidersSchemaOption` here as well, no?

2021-08-12 20:51 UTC, radeksimko commented on tfexec/providers_schema_test.go
> +	tf, err := NewTerraform(td, tfVersion(t, testutil.Latest014))
I remember there were some format changes at some point - is it perhaps safer to test both 0.12 and >=0.14 which introduced the format change?

2021-08-12 20:51 UTC, radeksimko commented on tfexec/workspace_list.go
> +	// TODO: [DIR] param option
I think this is no longer relevant?
```suggestion
```

2021-08-12 20:51 UTC, radeksimko commented on tfexec/workspace_list.go
>  	// TODO: [DIR] param option
```suggestion
```
That doesn't seem relevant anymore

2022-03-12 18:22 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform-exec?pullRequest=100)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-exec?pullRequest=100)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-exec?pullRequest=100).</sub>

2024-07-03 19:48 UTC, bflad commented
Someone can recreate this, if they wish.

2024-07-03 19:48 UTC, closed without merging