Console
hashicorp/terraform-exec pull request #64
Opened 2020-08-31 13:43 UTC by paultyng

2021-01-15 14:12 UTC, paultyng commented
The windows handling is fixed upstream so this should work on windows in 0.15+

2021-03-10 17:14 UTC, radeksimko requested changes
Was there any particular use case you had in mind for this command? I think we might eventually need it in Terraform LS, although I can't say for certain at this point.

Regardless of the needs, the output from `terraform console` actually may _not_ always be valid HCL syntax.

With that in mind I can imagine two ways forward in the near future:

1. We can close this PR unmerged and reopen the conversation later, when we have well-defined use cases for it - at which point we could also reopen the conversation about `console` supporting JSON output
2. Reimplement `ConsoleJSON` as `Console` which returns plain stdout as-is, review and merge.

I'm leaning more towards (1) unless there is a clear use case for this, but I'm interested to hear your opinion @paultyng

2021-03-10 17:18 UTC, paultyng commented
I thought this may be an easier way to do state inspection or things like testing / consul-tf-sync, without needing to worry about outputs, but I stopped pursuing it once I hit the windows stumbling block. It may be worth picking up once 1.0 is out, but until then its still just going to be broken for a decent portion of the audience, so you could probably just close.

2021-03-10 17:38 UTC, radeksimko commented
> but until then its still just going to be broken for a decent portion of the audience, so you could probably just close.

We could just gate it on TF 0.15+ and `GOOS` = `windows` or something.

I will ask the TF SDK and Consul teams about the needs and use cases and decide based on that.

Thanks for sharing the context!

2021-03-10 18:01 UTC, radeksimko commented
Both TF SDK and relevant Consul team told me that they don't have need for `terraform console` integration at this point, so I'm going to close this PR, but as mentioned I'd be happy to revisit once we have more specific use case in mind, so that we can also design the API around it.

Thank you for the effort invested into the PR.

2021-03-10 18:01 UTC, closed without merging